# Site settings
title:       Adrian Juarez
email:       aejuarez@outlook.com
author:      Adrian Juarez
description: ""
baseurl:     ""
url:         "http://www.aejuarez.com"

# Google analytics
google_analytics: UA-60996000-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: aejuarez

# Social icons
show_social_icons: true
github_username: aejuarez
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username: aejuarez
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
